### ISSUE TITLE
Are any release versions planned?

### ISSUE THREAD

**Issue by njlr** [martinmoene/ring-span-lite#1]

**Comment by martinmoene** [comment]
Code is kind of stable now (while nothing is happening at the sg14 side). Want to finish the Readme before making a release. Might take several days.

**Comment by njlr** [comment]
OK, no problem. I am keen to port your projects to [Buckaroo](https://github.com/LoopPerfect/buckaroo), since they are great building-blocks that I think people will benefit from. I'll check back in a few days once a release tag is available. Thanks!

**Comment by martinmoene** [comment]
@njlr created [first release](https://github.com/martinmoene/ring-span-lite/releases/tag/v0.0.0).

**Comment by martinmoene** [comment]
Buck build has been added per PR #4 , thanks to Nick La Rooy @njlr
