### ISSUE TITLE
Add capacity-is-always-power-of-2 mode for normalize_()

### ISSUE THREAD

**Issue by dcolascione** [martinmoene/ring-span-lite#22]
ring_span's normalize_() function uses the modulus operator, which emits a division instruction on most architectures. Division is slow: for example, on a Ryzen, division might take 8-13 cycles while add and subtract might take only one or two. Can ring_span gain a template parameter that makes it assume the capacity is power of two and compute normalize_ with masking instead of modulus?

(Using __builtin_unreachable() doesn't seem sufficient to make the recent GCC or Clang optimize the modulus to masking.)

**Comment by martinmoene** [comment]
@dcolascione Thanks for your suggestion.

Have to look into/think about it a bit.

**Comment by martinmoene** [comment]
_Comment WIP_

@dcolascione's [code comment](https://github.com/martinmoene/ring-span-lite/commit/ed1a600162662110e246ead8d6eb5517d9169a8a#commitcomment-53222527)  on template parameter to control implementation of `normalize_()`.

**Comment by martinmoene** [comment]
Available in [release 0.5.0](https://github.com/martinmoene/ring-span-lite/releases/tag/v0.5.0).
