### ISSUE TITLE
Empty base optimization for m_popper

### ISSUE THREAD

**Issue by dcolascione** [martinmoene/ring-span-lite#23]
Right now, popper is a field, m_popper. We store a byte for m_popper even though the popper is usually stateless. If the popper were instead a base class, there would be no size penalty in the case that m_popper has no state.

**Comment by Quuxplusone** [comment]
IMO, since C++20 introduces `[[no_unique_address]]` for this purpose, I think it would be a reasonable solution to use `[[no_unique_address]]` in C++20 (or whenever the compiler supports a similar attribute) but not bother with EBO when the attribute isn't available.

I agree that if `ring_span` were still on-track-for-standardization, we'd definitely specify the-member-whose-exposition-only-name-is-`m_popper` as `[[no_unique_address]]`. :)

**Comment by dcolascione** [comment]
Doing it that way would make the C++20 version ABI-incompatible with the C++17 version --- doing it with EBO would work in all versions of C++.

**Comment by martinmoene** [comment]
Thanks for this interesting input... makes me think of `nsrs_CONFIG_POPPER_EMPTY_BASE_CLASS`  :)

**Comment by martinmoene** [comment]
[Comment on commit by @dcolascione](https://github.com/martinmoene/ring-span-lite/commit/8ec18228d81b18668b350eb6a975c67a1dbf54da#commitcomment-53377216):

> I don't understand why there's a configuration flag here. The empty base optimization works on all versions of C++, even C++98. Why would anyone want to disable it? Sure, in C++20, we could use the attribute, but the EBO still works in C++20 without it. What's the downside to just using EBO unconditionally everywhere? Seems a lot simpler to me.

The origin for flag `nsrs_CONFIG_POPPER_EMPTY_BASE_CLASS` lies in "ring-span lite* being based on [proposal p0059](http://wg21.link/p0059). In Readme section [In a nutshell](https://github.com/martinmoene/ring-span-lite/tree/master#in-a-nutshell) I mention my intention to follow the development of that proposal. 

Although that proposal appears to not be actively pursued at the moment, I'm somewhat hesitant to deviate from that path right now. I prefer to allow some time and possibly gather some (more) feedback to base my decisions on.

**Comment by martinmoene** [comment]
Addressed in [Release 0.6.0](https://github.com/martinmoene/ring-span-lite/releases/tag/v0.6.0).
