### ISSUE TITLE
Compile issue in example

### ISSUE THREAD

**Issue by DougRogers** [martinmoene/ring-span-lite#24]
In example 03-make-ring-span.cpp, if you define PROVIDE_MAKE_RING_SPAN_FROM_GENERIC_CONTAINER

You will get a compile error.  

At line 156, the end of namespace should come before the #endif

156: #endif // PROVIDE_MAKE_RING_SPAN_FROM_GENERIC_CONTAINER
157:
158: } // namespace nonstd

**Comment by martinmoene** [comment]
Thanks for the heads-up!
