### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by mattreecebentley** [martinmoene/ring-span-lite#8]
Source implementation is Guy Davidson and Arthur O'Dwyer, not solely arthur. The initial implementation was by Guy, and he is prrimary force behind the C++ proposal.
Also, you might want to take a look at plf::colony for correcting compiler feature detection.

**Comment by martinmoene** [comment]
> Also, you might want to take a look at plf::colony for correcting compiler feature detection.

@mattreecebentley  Anything specific you noticed?

**Comment by mattreecebentley** [comment]
Ah ok cool - I didn't check the link and made the assumption the link was to the SG14 - no harm intended. Probably some credit still due to guy as he wrote the spec, but yeah.

@martinmoene If you take a look at the first section of any of the plf:: library headers, you'll find the compiler feature detection code. There's a bunch of cases where C++11 is specified as available but certain features are not - both for gcc and when other libraries are using libstdc++.
Might be worth just copy-pasting that section then adapting to suit.

**Comment by mattreecebentley** [comment]
ps. Obviously boost config is the best reference for this, but it spralls across 100s of files. I'm only trying to adapt to the most common compilers.
